// <auto-generated />
namespace OOD_project_2026.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.6.0-preview1-final")]
    public sealed partial class Rank : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Rank));
        
        string IMigrationMetadata.Id
        {
            get { return "202604162356066_Rank"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
